# -*- coding: utf-8 -*-
"""product_submission_lifecycle_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diMN6wXN-h5b45dK20FtxNYDVpr3Hbxh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#loading the datasets
from google.colab import files

uploaded = files.upload()

#reading the datasets
products = pd.read_csv("/content/products.csv")
submissions = pd.read_csv("/content/submissions.csv")
lifecycle_events = pd.read_csv("/content/lifecycle_events.csv")
regions = pd.read_csv("/content/regions.csv")
product_categories = pd.read_csv("/content/product_categories.csv")
submission_targets = pd.read_csv("/content/submission_targets.csv")

print("Products:", products.shape)
print("Submissions:", submissions.shape)
print("Lifecycle Events:", lifecycle_events.shape)
print("Regions:", regions.shape)
print("Product Categories:", product_categories.shape)
print("Submission Targets:", submission_targets.shape)

submissions.head()

submissions.info()

#converting date columns
submissions["Submission_Date"] = pd.to_datetime(
    submissions["Submission_Date"]
)

submissions["Approval_Date"] = pd.to_datetime(
    submissions["Approval_Date"]
)

print("Date columns converted successfully")
print(submissions[["Submission_Date", "Approval_Date"]].dtypes)

#converting submission delayed to Boolean
submissions["Submission_Delayed"] = (
    submissions["Submission_Delayed"] == "Yes"
)

print(submissions["Submission_Delayed"].value_counts())
print(submissions["Submission_Delayed"].dtype)

#checking missing values
missing = submissions.isna().sum()

print(missing)

#creating variable columns for analysis
submissions["Review_Variance_Days"] = (
    submissions["Review_Days"] - submissions["Target_Review_Days"]
)

submissions["Review_Within_Target"] = (
    submissions["Review_Days"] <= submissions["Target_Review_Days"]
)

submissions[[
    "Review_Days",
    "Target_Review_Days",
    "Review_Variance_Days",
    "Review_Within_Target"
]].head()

#descriptive stats
submissions[
    [
        "Risk_Score",
        "Review_Days",
        "Target_Review_Days",
        "Review_Variance_Days"
    ]
].describe()

#Review days distribution
plt.figure(figsize=(10, 6))

sns.histplot(
    submissions["Review_Days"],
    bins=30,
    kde=True
)

plt.title("Distribution of Submission Review Days")
plt.xlabel("Review Days")
plt.ylabel("Number of Submissions")

plt.show()

#Analyse review performance by submission type
review_by_type = (
    submissions
    .groupby("Submission_Type")["Review_Days"]
    .mean()
    .sort_values(ascending=False)
)

print(review_by_type)

#average review variance by submission type
variance_by_type = (
    submissions
    .groupby("Submission_Type")["Review_Variance_Days"]
    .mean()
    .sort_values(ascending=False)
)

print(variance_by_type)

#Visualise review variance by submission type
plt.figure(figsize=(10, 6))

sns.barplot(
    x=variance_by_type.index,
    y=variance_by_type.values
)

plt.axhline(0, linewidth=1)

plt.title("Average Review Variance by Submission Type")
plt.xlabel("Submission Type")
plt.ylabel("Average Variance (Days)")
plt.xticks(rotation=30)

plt.show()

#Analyse delay rates by submission type
delay_by_type = (
    submissions
    .groupby("Submission_Type")["Submission_Delayed"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(delay_by_type)

# visualise delay rates by submission type
plt.figure(figsize=(10, 6))

sns.barplot(
    x=delay_by_type.index,
    y=delay_by_type.values
)

plt.title("Submission Delay Rate by Submission Type")
plt.xlabel("Submission Type")
plt.ylabel("Delay Rate (%)")
plt.xticks(rotation=30)

plt.show()

#Analyse review performance by region
submissions_region = submissions.merge(
    regions,
    on="Region_ID",
    how="left"
)

print(submissions_region[[
    "Region_ID",
    "Region"
]].drop_duplicates().sort_values("Region_ID"))

#analyse regional performance
regional_performance = (
    submissions_region
    .groupby("Region")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Approval_Rate=("Submission_Status", lambda x: (x == "Approved").mean() * 100),
        Delay_Rate=("Submission_Delayed", "mean"),
        Avg_Risk_Score=("Risk_Score", "mean")
    )
    .sort_values("Delay_Rate", ascending=False)
)

regional_performance["Delay_Rate"] = (
    regional_performance["Delay_Rate"] * 100
)

regional_performance.round(2)

# visualise regional delay rates
plt.figure(figsize=(10, 6))

sns.barplot(
    x=regional_performance.index,
    y=regional_performance["Delay_Rate"].values
)

plt.title("Submission Delay Rate by Region")
plt.xlabel("Region")
plt.ylabel("Delay Rate (%)")
plt.xticks(rotation=30)

plt.show()

#compare approval rates by region
approval_by_region = (
    submissions_region
    .groupby("Region")["Submission_Status"]
    .apply(lambda x: (x == "Approved").mean() * 100)
    .sort_values(ascending=False)
)

print(approval_by_region.round(2))

#Visualize approval rate by region
plt.figure(figsize=(10, 6))

sns.barplot(
    x=approval_by_region.index,
    y=approval_by_region.values
)

plt.title("Submission Approval Rate by Region")
plt.xlabel("Region")
plt.ylabel("Approval Rate (%)")
plt.xticks(rotation=30)

plt.show()

#Analyze risk categories
review_by_risk = (
    submissions
    .groupby("Risk_Category")["Review_Days"]
    .mean()
    .sort_values(ascending=False)
)

print(review_by_risk.round(2))

#Compare delay rates by risk category
delay_by_risk = (
    submissions
    .groupby("Risk_Category")["Submission_Delayed"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(delay_by_risk.round(2))

#Visualize delay rate by risk category
plt.figure(figsize=(8, 5))

sns.barplot(
    x=delay_by_risk.index,
    y=delay_by_risk.values
)

plt.title("Submission Delay Rate by Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("Delay Rate (%)")

plt.show()

#Compare approval rates by risk category
approval_by_risk = (
    submissions
    .groupby("Risk_Category")["Submission_Status"]
    .apply(lambda x: (x == "Approved").mean() * 100)
    .sort_values(ascending=False)
)

print(approval_by_risk.round(2))

#Visualize approval rate by risk category
plt.figure(figsize=(8, 5))

sns.barplot(
    x=approval_by_risk.index,
    y=approval_by_risk.values
)

plt.title("Submission Approval Rate by Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("Approval Rate (%)")

plt.show()

#Analyze priority
review_by_priority = (
    submissions
    .groupby("Priority")["Review_Days"]
    .mean()
    .sort_values(ascending=False)
)

print(review_by_priority.round(2))

#Compare delay rates by priority
delay_by_priority = (
    submissions
    .groupby("Priority")["Submission_Delayed"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(delay_by_priority.round(2))

#Visualize priority delay rates
plt.figure(figsize=(8, 5))

sns.barplot(
    x=delay_by_priority.index,
    y=delay_by_priority.values
)

plt.title("Submission Delay Rate by Priority")
plt.xlabel("Priority")
plt.ylabel("Delay Rate (%)")

plt.show()

#Analyze the monthly trend
monthly_performance = (
    submissions
    .assign(Month=submissions["Submission_Date"].dt.to_period("M").astype(str))
    .groupby("Month")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Approval_Rate=("Submission_Status", lambda x: (x == "Approved").mean() * 100),
        Delay_Rate=("Submission_Delayed", "mean")
    )
)

monthly_performance["Delay_Rate"] = (
    monthly_performance["Delay_Rate"] * 100
)

monthly_performance.round(2).head(10)

#visualise Monthly approval-rate trend
plt.figure(figsize=(14, 6))

plt.plot(
    monthly_performance.index,
    monthly_performance["Approval_Rate"],
    marker="o"
)

plt.title("Monthly Submission Approval Rate")
plt.xlabel("Month")
plt.ylabel("Approval Rate (%)")
plt.xticks(rotation=45)

plt.show()

#visualise Monthly delay-rate trend
plt.figure(figsize=(14, 6))

plt.plot(
    monthly_performance.index,
    monthly_performance["Delay_Rate"],
    marker="o"
)

plt.title("Monthly Submission Delay Rate")
plt.xlabel("Month")
plt.ylabel("Delay Rate (%)")
plt.xticks(rotation=45)

plt.show()

#Analyze the lifecycle events
lifecycle_stage_summary = (
    lifecycle_events
    .groupby("Lifecycle_Stage")["Stage_Duration_Days"]
    .agg(
        Total_Events="count",
        Avg_Duration_Days="mean"
    )
    .sort_values("Avg_Duration_Days", ascending=False)
)

print(lifecycle_stage_summary.round(2))

#Visualize lifecycle-stage duration
plt.figure(figsize=(10, 6))

sns.barplot(
    x=lifecycle_stage_summary.index,
    y=lifecycle_stage_summary["Avg_Duration_Days"]
)

plt.title("Average Lifecycle Stage Duration")
plt.xlabel("Lifecycle Stage")
plt.ylabel("Average Duration (Days)")
plt.xticks(rotation=30)

plt.show()

#Check lifecycle event status
lifecycle_events["Event_Status"].value_counts()

#Check missing approval dates by status
approval_date_quality = (
    submissions
    .groupby("Submission_Status")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Missing_Approval_Dates=("Approval_Date", lambda x: x.isna().sum())
    )
)

approval_date_quality["Missing_Rate"] = (
    approval_date_quality["Missing_Approval_Dates"]
    / approval_date_quality["Total_Submissions"]
    * 100
)

print(approval_date_quality.round(2))

#Calculate the overall data-quality impact
unexpected_missing_approval = submissions[
    (submissions["Submission_Status"] != "Under Review") &
    (submissions["Approval_Date"].isna())
]

print("Unexpected missing approval dates:", len(unexpected_missing_approval))
print(
    "Percentage of all submissions:",
    round(len(unexpected_missing_approval) / len(submissions) * 100, 2),
    "%"
)

# checking unknown values
print("Unknown Submission Types:")
print(submissions["Submission_Type"].value_counts())

print("\nRisk Category values:")
print(submissions["Risk_Category"].value_counts())

#Creating clean analysis categories
submissions["Submission_Type_Clean"] = (
    submissions["Submission_Type"].replace({
        "Unknown": np.nan
    })
)

submissions["Risk_Category_Clean"] = (
    submissions["Risk_Category"].replace({
        "Unknow": np.nan
    })
)

print("Clean columns created successfully")
print("Missing Submission Type:", submissions["Submission_Type_Clean"].isna().sum())
print("Missing Risk Category:", submissions["Risk_Category_Clean"].isna().sum())

#Creating a clean business-analysis dataset
clean_submissions = submissions.dropna(
    subset=["Submission_Type_Clean", "Risk_Category_Clean"]
).copy()

print("Original rows:", len(submissions))
print("Clean analysis rows:", len(clean_submissions))
print("Rows excluded:", len(submissions) - len(clean_submissions))

#Analyze the relationship between risk score and review time
correlation = clean_submissions[
    ["Risk_Score", "Review_Days"]
].corr()

print(correlation.round(3))

#visualise the relationship between risk score and review time
plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=clean_submissions,
    x="Risk_Score",
    y="Review_Days",
    alpha=0.3
)

plt.title("Risk Score vs. Submission Review Days")
plt.xlabel("Risk Score")
plt.ylabel("Review Days")
plt.show()

#Identify the highest-risk submissions
high_risk_submissions = (
    clean_submissions
    .sort_values(
        ["Risk_Score", "Review_Days"],
        ascending=[False, False]
    )
    [["Submission_ID", "Risk_Score", "Risk_Category",
      "Submission_Type_Clean", "Review_Days",
      "Target_Review_Days", "Submission_Delayed"]]
    .head(20)
)

high_risk_submissions

#Create a risk-vs-delay summary
risk_delay_summary = (
    clean_submissions
    .groupby("Risk_Category_Clean")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Risk_Score=("Risk_Score", "mean"),
        Avg_Review_Days=("Review_Days", "mean"),
        Delay_Rate=("Submission_Delayed", "mean")
    )
)

risk_delay_summary["Delay_Rate"] *= 100

risk_delay_summary.round(2)

#Building the Region × Submission Type analysis
submissions_region["Submission_Type_Clean"] = (
    submissions_region["Submission_Type"].replace({"Unknown": np.nan})
)

print(submissions_region["Submission_Type_Clean"].value_counts(dropna=False))
region_type_analysis = (
    submissions_region[
        submissions_region["Submission_Type_Clean"].notna()
    ]
    .groupby(["Region", "Submission_Type_Clean"])
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Delay_Rate=("Submission_Delayed", "mean"),
        Approval_Rate=(
            "Submission_Status",
            lambda x: (x == "Approved").mean()
        )
    )
)

region_type_analysis["Delay_Rate"] *= 100
region_type_analysis["Approval_Rate"] *= 100

region_type_analysis = region_type_analysis.sort_values(
    "Delay_Rate",
    ascending=False
)

region_type_analysis.round(2).head(15)

#Creating a heatmap of delay rates
heatmap_data = region_type_analysis["Delay_Rate"].unstack()

plt.figure(figsize=(12, 6))

sns.heatmap(
    heatmap_data,
    annot=True,
    fmt=".1f",
    cmap="Blues"
)

plt.title("Delay Rate by Region and Submission Type")
plt.xlabel("Submission Type")
plt.ylabel("Region")
plt.show()

#creating the product-category mapping
products_enriched = products.merge(
    product_categories,
    on="Product_Category_ID",
    how="left"
)

print(products_enriched.shape)
print(products_enriched[[
    "Product_ID",
    "Product_Category",
    "Business_Unit",
    "Product_Type",
    "Lifecycle_Status",
    "Risk_Category"
]].head())

#Joining product information to submissions
submissions_enriched = submissions_region.merge(
    products_enriched[
        [
            "Product_ID",
            "Product_Category",
            "Business_Unit",
            "Product_Type",
            "Development_Date",
            "Lifecycle_Status"
        ]
    ],
    on="Product_ID",
    how="left"
)

print("Rows:", len(submissions_enriched))
print("Columns:", len(submissions_enriched.columns))
print(submissions_enriched.head())

#Analyze performance by product category
category_performance = (
    submissions_enriched
    .groupby("Product_Category")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Delay_Rate=("Submission_Delayed", "mean"),
        Approval_Rate=(
            "Submission_Status",
            lambda x: (x == "Approved").mean()
        )
    )
)

category_performance["Delay_Rate"] *= 100
category_performance["Approval_Rate"] *= 100

category_performance = category_performance.sort_values(
    "Delay_Rate",
    ascending=False
)

category_performance.round(2)

#Analyze performance by Business Unit
business_unit_performance = (
    submissions_enriched
    .groupby("Business_Unit")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Delay_Rate=("Submission_Delayed", "mean"),
        Approval_Rate=(
            "Submission_Status",
            lambda x: (x == "Approved").mean()
        )
    )
)

business_unit_performance["Delay_Rate"] *= 100
business_unit_performance["Approval_Rate"] *= 100

business_unit_performance = business_unit_performance.sort_values(
    "Delay_Rate",
    ascending=False
)

business_unit_performance.round(2)

#Analyze performance by regulatory area
regulatory_area_performance = (
    submissions_enriched
    .groupby("Regulatory_Area")
    .agg(
        Total_Submissions=("Submission_ID", "count"),
        Avg_Review_Days=("Review_Days", "mean"),
        Delay_Rate=("Submission_Delayed", "mean"),
        Approval_Rate=(
            "Submission_Status",
            lambda x: (x == "Approved").mean()
        )
    )
)

regulatory_area_performance["Delay_Rate"] *= 100
regulatory_area_performance["Approval_Rate"] *= 100

regulatory_area_performance = regulatory_area_performance.sort_values(
    "Delay_Rate",
    ascending=False
)

regulatory_area_performance.round(2)

#Creating the final regulatory-area visualization
plt.figure(figsize=(10, 6))

sns.barplot(
    data=regulatory_area_performance.reset_index(),
    x="Regulatory_Area",
    y="Delay_Rate"
)

plt.title("Submission Delay Rate by Regulatory Area")
plt.xlabel("Regulatory Area")
plt.ylabel("Delay Rate (%)")
plt.show()

#Creating the final Power BI dataset
powerbi_data = submissions_enriched.copy()

print("Rows:", len(powerbi_data))
print("Columns:", len(powerbi_data.columns))
print(powerbi_data.columns.tolist())

#exporting the powe BI dataset
powerbi_data.to_csv(
    "/content/submissions_enriched.csv",
    index=False
)

print("File saved successfully.")